# Generated by Django 3.1 on 2020-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[['MO', 'Motors'], ['FA', 'Fashion'], ['ME', 'Media'], ['EL', 'Electronics'], ['AR', 'Art'], ['HO', 'Home'], ['SP', 'Sports'], ['TO', 'Toys'], ['BU', 'Business'], ['HE', 'Health'], ['OT', 'Other']], max_length=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Enter description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Enter title', max_length=64),
        ),
    ]
